### ISSUE TITLE
State Diagram not supported in Mermaid?

### ISSUE THREAD

**Issue by lespea** [vjeantet/hugo-theme-docport#22]
I'm not sure if the version of mermaid bundled is just very old or it's some other issue, but trying to make a [state diagram](http://mermaid-js.github.io/mermaid/diagrams-and-syntax-and-examples/stateDiagram.html) doesn't seem to work.

**Comment by vjeantet** [comment]
Hi @lespea the version of mermaid was very old.
This is now fixed, you can see a state diagram example here : https://docport.netlify.app/shortcodes/mermaid/#state-diagram

**Comment by lespea** [comment]
Awesome thanks!
