### ISSUE TITLE
add line number and copy button for code blocks, will support?

### ISSUE THREAD

**Issue by yyangdid** [vjeantet/hugo-theme-docport#24]
add line number and copy button for code blocks, will support?

**Comment by vjeantet** [comment]
good idea ! , you can implement this and share this with the community in a pull request.

**Comment by NoSugarCoffee** [comment]
have same needs，and code block can align with title and content？

![image](https://user-images.githubusercontent.com/25247325/126799264-89e66d1c-d9d4-4e71-a095-f7aa1b8e0f13.png)
