### ISSUE TITLE
How to move search bar to different place?

### ISSUE THREAD

**Issue by WuZhuoran** [vjeantet/hugo-theme-docport#25]
Hi,

Now the search bar is placed at top of the left menu,

I want to put search bar at the top the page, something like this,

<img width="1276" alt="Screen Shot 2020-10-02 at 2 50 12 PM" src="https://user-images.githubusercontent.com/8717187/94972635-954bc400-04be-11eb-91c9-f997aa067061.png">

How to implement this? 

Thank you

**Comment by vjeantet** [comment]
Hello @WuZhuoran this is not implemented in current theme, but you can implement it by copying `themes/docport/layouts/partials/body-article-content.html` to your `layouts/partials/body-article-content.html` and add the search bar HTML on top of this file.

The HTML part which is in charge of display the search box is in this file : `themes/docport/layouts/partials/body-sidebar.html`
