### ISSUE TITLE
Badge rendered as plain text

### ISSUE THREAD

**Issue by Nigh** [vjeantet/hugo-theme-docport#26]
Copied badge page content in example site to my page.

All the badge text rendered to plain text.

**Comment by vjeantet** [comment]
Hello @Nigh , can you elaborate on your issue ?
can i have a copy of your content ?

**Comment by Nigh** [comment]
@vjeantet I reproduced the problem by following these steps.
1. `hugo new site .`
2. copy the content of [content.zip](https://github.com/vjeantet/hugo-theme-docport/files/5456080/content.zip) into `content` folder
3. add `theme = "docport"` in `config.toml`
4. `hugo server`
5. rendered as below
![hugo_debug](https://user-images.githubusercontent.com/1407471/97524194-06f43080-19df-11eb-8b24-1ddca62d18d8.png)

**Comment by vjeantet** [comment]
found ! Add the following line in your config.toml file and it will work.

```toml
[markup.goldmark.renderer]
unsafe = true
```

**Comment by vjeantet** [comment]
another workaround if you don't want to use unsafe mode :

in you content, use 
```{{< badge >}}primary _(default)_{{< /badge >}}``` 
instead of 
```{{% badge %}}primary _(default)_{{% /badge %}}```

**Comment by Nigh** [comment]
Solved.
